#include "gpu_surface.h"
#include "worker_pipe.h"
// A real D3D12 swapchain host, loaded through staged ReShade dxgi.dll.
static void wait(ID3D12Device* d,ID3D12CommandQueue* q){ComPtr<ID3D12Fence> f;hr(d->CreateFence(0,D3D12_FENCE_FLAG_NONE,IID_PPV_ARGS(&f)));hr(q->Signal(f.Get(),1));HANDLE e=CreateEventW(nullptr,FALSE,FALSE,nullptr);hr(f->SetEventOnCompletion(1,e));if(WaitForSingleObject(e,2000)!=WAIT_OBJECT_0)throw std::runtime_error("host GPU timeout; no retry");CloseHandle(e);hr(d->GetDeviceRemovedReason());}
static std::vector<uint8_t> pixels(ID3D12Device* d,ID3D12CommandQueue* q,ID3D12Resource* t){
    auto td=t->GetDesc();D3D12_PLACED_SUBRESOURCE_FOOTPRINT fp{};UINT rows;UINT64 rb,bytes;d->GetCopyableFootprints(&td,0,1,0,&fp,&rows,&rb,&bytes);
    D3D12_RESOURCE_DESC bd{};bd.Dimension=D3D12_RESOURCE_DIMENSION_BUFFER;bd.Width=bytes;bd.Height=1;bd.DepthOrArraySize=1;bd.MipLevels=1;bd.SampleDesc.Count=1;bd.Layout=D3D12_TEXTURE_LAYOUT_ROW_MAJOR;
    D3D12_HEAP_PROPERTIES hp{};hp.Type=D3D12_HEAP_TYPE_READBACK;ComPtr<ID3D12Resource> down;hr(d->CreateCommittedResource(&hp,D3D12_HEAP_FLAG_NONE,&bd,D3D12_RESOURCE_STATE_COPY_DEST,nullptr,IID_PPV_ARGS(&down)));
    ComPtr<ID3D12CommandAllocator> a;ComPtr<ID3D12GraphicsCommandList> c;hr(d->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT,IID_PPV_ARGS(&a)));hr(d->CreateCommandList(0,D3D12_COMMAND_LIST_TYPE_DIRECT,a.Get(),nullptr,IID_PPV_ARGS(&c)));
    D3D12_TEXTURE_COPY_LOCATION src{},dst{};src.pResource=t;src.Type=D3D12_TEXTURE_COPY_TYPE_SUBRESOURCE_INDEX;dst.pResource=down.Get();dst.Type=D3D12_TEXTURE_COPY_TYPE_PLACED_FOOTPRINT;dst.PlacedFootprint=fp;
    transition(c.Get(),t,D3D12_RESOURCE_STATE_PRESENT,D3D12_RESOURCE_STATE_COPY_SOURCE);c->CopyTextureRegion(&dst,0,0,0,&src,nullptr);transition(c.Get(),t,D3D12_RESOURCE_STATE_COPY_SOURCE,D3D12_RESOURCE_STATE_PRESENT);hr(c->Close());ID3D12CommandList* lists[]={c.Get()};q->ExecuteCommandLists(1,lists);wait(d,q);
    void* data;D3D12_RANGE r{0,size_t(bytes)};hr(down->Map(0,&r,&data));std::vector<uint8_t> result(td.Width*td.Height*4);for(UINT y=0;y<rows;++y)std::memcpy(result.data()+y*rb,static_cast<char*>(data)+fp.Offset+y*fp.Footprint.RowPitch,rb);D3D12_RANGE none{};down->Unmap(0,&none);return result;
}
int wmain(int argc,wchar_t** argv){
    if(argc==2&&!wcscmp(argv[1],L"--cpu-selftest")){try{using namespace native_preview;if(number("{\"pid\":123}","pid")!=123)return 1;for(auto s:{"{\"pid\":-1}","{\"pid\":1,\"pid\":2}","{\"pid\":true}","{\"pid\":18446744073709551616}"}){bool rejected=false;try{number(s,"pid");}catch(...){rejected=true;}if(!rejected)return 1;}puts("CPU protocol checks passed");return 0;}catch(...){return 1;}}
    if(argc!=5&&argc!=6)return 2;UINT w=std::stoul(argv[2]),h=std::stoul(argv[3]),n=std::stoul(argv[4]);auto format=argc==6?DXGI_FORMAT(std::stoul(argv[5])):DXGI_FORMAT_R8G8B8A8_UNORM;auto out=std::filesystem::path(argv[1]);if(!std::filesystem::is_directory(out)||w>3840||h>2160||!w||!h||n>180||(format!=DXGI_FORMAT_R8G8B8A8_UNORM&&format!=DXGI_FORMAT_R10G10B10A2_UNORM))return 2;
    try{
        ComPtr<ID3D12Debug> debug;hr(D3D12GetDebugInterface(IID_PPV_ARGS(&debug)));debug->EnableDebugLayer();
        ComPtr<IDXGIFactory4> f;hr(CreateDXGIFactory1(IID_PPV_ARGS(&f)));ComPtr<IDXGIAdapter1> adapter;
        for(UINT i=0;;++i){adapter.Reset();hr(f->EnumAdapters1(i,&adapter));DXGI_ADAPTER_DESC1 ad{};hr(adapter->GetDesc1(&ad));if(ad.VendorId==0x1002&&!(ad.Flags&DXGI_ADAPTER_FLAG_SOFTWARE))break;}
        ComPtr<ID3D12Device> d;hr(D3D12CreateDevice(adapter.Get(),D3D_FEATURE_LEVEL_12_0,IID_PPV_ARGS(&d)));ComPtr<ID3D12InfoQueue> info;hr(d.As(&info));ComPtr<ID3D12CommandQueue> q;D3D12_COMMAND_QUEUE_DESC qd{};hr(d->CreateCommandQueue(&qd,IID_PPV_ARGS(&q)));
        WNDCLASSW wc{};wc.lpfnWndProc=DefWindowProcW;wc.hInstance=GetModuleHandleW(nullptr);wc.lpszClassName=L"NativeReShadeTest";RegisterClassW(&wc);HWND hwnd=CreateWindowW(wc.lpszClassName,L"Native ROCm ReShade integration test",WS_OVERLAPPEDWINDOW,80,80,int(w)+20,int(h)+50,nullptr,nullptr,wc.hInstance,nullptr);ShowWindow(hwnd,SW_SHOWNOACTIVATE);
        DXGI_SWAP_CHAIN_DESC1 sd{};sd.Width=w;sd.Height=h;sd.Format=format;sd.SampleDesc.Count=1;sd.BufferUsage=DXGI_USAGE_RENDER_TARGET_OUTPUT;sd.BufferCount=2;sd.SwapEffect=DXGI_SWAP_EFFECT_FLIP_DISCARD;ComPtr<IDXGISwapChain1> initial;hr(f->CreateSwapChainForHwnd(q.Get(),hwnd,&sd,nullptr,nullptr,&initial));ComPtr<IDXGISwapChain3> swap;hr(initial.As(&swap));hr(swap->SetColorSpace1(DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709));
        D3D12_DESCRIPTOR_HEAP_DESC hd{};hd.Type=D3D12_DESCRIPTOR_HEAP_TYPE_RTV;hd.NumDescriptors=1;ComPtr<ID3D12DescriptorHeap> heap;hr(d->CreateDescriptorHeap(&hd,IID_PPV_ARGS(&heap)));auto rtv=heap->GetCPUDescriptorHandleForHeapStart();
        for(UINT i=0;i<n;++i){MSG m;while(PeekMessageW(&m,nullptr,0,0,PM_REMOVE)){TranslateMessage(&m);DispatchMessageW(&m);}ComPtr<ID3D12Resource> target;hr(swap->GetBuffer(swap->GetCurrentBackBufferIndex(),IID_PPV_ARGS(&target)));d->CreateRenderTargetView(target.Get(),nullptr,rtv);
            ComPtr<ID3D12CommandAllocator> a;ComPtr<ID3D12GraphicsCommandList> c;hr(d->CreateCommandAllocator(qd.Type,IID_PPV_ARGS(&a)));hr(d->CreateCommandList(0,qd.Type,a.Get(),nullptr,IID_PPV_ARGS(&c)));transition(c.Get(),target.Get(),D3D12_RESOURCE_STATE_PRESENT,D3D12_RESOURCE_STATE_RENDER_TARGET);
            for(UINT x=0;x<8;++x){D3D12_RECT rect{LONG(x*w/8),0,LONG((x+1)*w/8),LONG(h)};float color[]={float(x+1)/10,float(i%2+2)/10,float(8-x)/10,1};c->ClearRenderTargetView(rtv,color,1,&rect);}transition(c.Get(),target.Get(),D3D12_RESOURCE_STATE_RENDER_TARGET,D3D12_RESOURCE_STATE_PRESENT);hr(c->Close());ID3D12CommandList* lists[]={c.Get()};q->ExecuteCommandLists(1,lists);wait(d.Get(),q.Get());
            hr(swap->Present(1,0));wait(d.Get(),q.Get());auto raw=pixels(d.Get(),q.Get(),target.Get());std::ofstream file(out/(L"frame"+std::to_wstring(i)+L".rgba8"),std::ios::binary);file.write(reinterpret_cast<const char*>(raw.data()),raw.size());Sleep(30);
        }
        swap.Reset();initial.Reset();DestroyWindow(hwnd);wait(d.Get(),q.Get());UINT errors=0;std::ofstream log(out/L"debug_messages.txt");for(UINT64 i=0;i<info->GetNumStoredMessages();++i){SIZE_T bytes=0;info->GetMessage(i,nullptr,&bytes);std::vector<uint8_t> raw(bytes);auto* m=reinterpret_cast<D3D12_MESSAGE*>(raw.data());info->GetMessage(i,m,&bytes);if(m->Severity<=D3D12_MESSAGE_SEVERITY_WARNING)log<<m->pDescription<<'\n';if(m->Severity<=D3D12_MESSAGE_SEVERITY_ERROR)++errors;}
        std::ofstream(out/L"host.json")<<"{\"frames\":"<<n<<",\"d3d12_errors\":"<<errors<<",\"format\":"<<format<<",\"width\":"<<w<<",\"height\":"<<h<<"}";return errors?1:0;
    }catch(const std::exception& e){std::ofstream(out/L"host_failure.txt")<<e.what();std::fprintf(stderr,"%s\n",e.what());return 1;}
}
