#define main output_head_tail_surface_file_cli
#include "output_head_tail_surface_d3d12.cpp"
#undef main

namespace {
constexpr uint64_t kFullMainOffset = 13873152, kFullSkipOffset = 110592;
constexpr uint64_t kFullMainBytes = 2ull * 192 * 320 * 16, kFullSkipBytes = 96ull * 160 * 512;
constexpr uint64_t kFullFusedE4Bytes = 81ull * 49 * 2048;
constexpr uint64_t kFullHiddenBytes = 81ull * 49 * 4 * 2048;
constexpr uint64_t kFullProjectionBytes = 81ull * 49 * 48 * 16 * 8 * 2;
constexpr uint64_t kFullQkvBytes = 81ull * 49 * 64 * 32;
constexpr uint64_t kFullQkBytes = 81ull * 49 * 32 * 16 * 8 * 2;

struct FullMetrics { uint64_t mismatches=0, nonFinite=0; double mean=0; float maximum=0; };
FullMetrics CompareFull(const std::vector<uint8_t>& a,const std::vector<uint8_t>& e){
  FullMetrics m{}; const auto* ah=(const uint16_t*)a.data(); const auto* eh=(const uint16_t*)e.data(); double sum=0;
  for(size_t i=0;i<a.size()/2;++i){m.mismatches+=ah[i]!=eh[i];float av=HalfToFloat(ah[i]);float d=std::abs(av-HalfToFloat(eh[i]));m.nonFinite+=!std::isfinite(av);sum+=d;m.maximum=std::max(m.maximum,d);}m.mean=sum/double(a.size()/2);return m;
}
std::vector<uint8_t> GetReadback(ID3D12Resource* resource,uint64_t bytes){std::vector<uint8_t> v(static_cast<size_t>(bytes));void* p=nullptr;D3D12_RANGE r{0,SIZE_T(bytes)};HR_CHECK(resource->Map(0,&r,&p));std::memcpy(v.data(),p,v.size());resource->Unmap(0,nullptr);return v;}
void Bind(ID3D12GraphicsCommandList* list,ID3D12PipelineState* pipeline,ID3D12Resource* a,ID3D12Resource* b,ID3D12Resource* c,ID3D12Resource* out0,ID3D12Resource* out1=nullptr){
  list->SetPipelineState(pipeline);if(a)list->SetComputeRootShaderResourceView(0,a->GetGPUVirtualAddress());if(b)list->SetComputeRootShaderResourceView(1,b->GetGPUVirtualAddress());if(c)list->SetComputeRootShaderResourceView(2,c->GetGPUVirtualAddress());if(out0)list->SetComputeRootUnorderedAccessView(3,out0->GetGPUVirtualAddress());if(out1)list->SetComputeRootUnorderedAccessView(4,out1->GetGPUVirtualAddress());
}
}

int main(int argc,char** argv){try{
  if(argc!=13){std::fprintf(stderr,"usage: output_head_full_d3d12 <activation_arena.raw> <model_arena.raw> <base.raw|-> <expected_first128.raw> <expected_projection.raw> <expected_qk.raw> <expected_attention.raw> <expected_projected.raw> <expected_residual.raw> <expected_surface.raw> <surface_out.raw> <manifest.json>\n");return 2;}
  auto mainFeature=ReadSlice(argv[1],kFullMainOffset,kFullMainBytes),skipFeature=ReadSlice(argv[1],kFullSkipOffset,kFullSkipBytes),head=ReadSlice(argv[2],kHeadOffset,kHeadBytes);
  auto base=std::string(argv[3])=="-"?std::vector<uint8_t>(size_t(kSurfaceBytes),0):Read(argv[3]);
  auto ef=Read(argv[4]),ep=Read(argv[5]),eqk=Read(argv[6]),ea=Read(argv[7]),eap=Read(argv[8]),er=Read(argv[9]),es=Read(argv[10]);
  if(base.size()!=kSurfaceBytes||ef.size()!=kProjectedBytes||ep.size()!=kFullProjectionBytes||eqk.size()!=kFullQkBytes||ea.size()!=kProjectedBytes||eap.size()!=kProjectedBytes||er.size()!=kResidualBytes||es.size()!=kSurfaceBytes)throw std::runtime_error("unexpected oracle size");

  ComPtr<IDXGIFactory7> factory;HR_CHECK(CreateDXGIFactory2(0,IID_PPV_ARGS(&factory)));ComPtr<IDXGIAdapter1> adapter;DXGI_ADAPTER_DESC1 ad{};bool found=false;
  for(UINT i=0;factory->EnumAdapters1(i,&adapter)!=DXGI_ERROR_NOT_FOUND;++i,adapter.Reset()){HR_CHECK(adapter->GetDesc1(&ad));if(!(ad.Flags&DXGI_ADAPTER_FLAG_SOFTWARE)&&ad.VendorId==0x1002){found=true;break;}}
  if(!found)throw std::runtime_error("AMD D3D12 adapter not found");ComPtr<ID3D12Device> device;HR_CHECK(D3D12CreateDevice(adapter.Get(),D3D_FEATURE_LEVEL_11_0,IID_PPV_ARGS(&device)));
  D3D12_ROOT_PARAMETER params[5]{};for(uint32_t i=0;i<3;++i){params[i].ParameterType=D3D12_ROOT_PARAMETER_TYPE_SRV;params[i].Descriptor.ShaderRegister=i;params[i].ShaderVisibility=D3D12_SHADER_VISIBILITY_ALL;}for(uint32_t i=3;i<5;++i){params[i].ParameterType=D3D12_ROOT_PARAMETER_TYPE_UAV;params[i].Descriptor.ShaderRegister=i-3;params[i].ShaderVisibility=D3D12_SHADER_VISIBILITY_ALL;}
  D3D12_ROOT_SIGNATURE_DESC rd{};rd.NumParameters=5;rd.pParameters=params;ComPtr<ID3DBlob> rb,re;HR_CHECK(D3D12SerializeRootSignature(&rd,D3D_ROOT_SIGNATURE_VERSION_1,&rb,&re));ComPtr<ID3D12RootSignature> root;HR_CHECK(device->CreateRootSignature(0,rb->GetBufferPointer(),rb->GetBufferSize(),IID_PPV_ARGS(&root)));
  fs::path build=fs::absolute(argv[0]).parent_path();auto make=[&](const char* n){return Pipeline(device.Get(),root.Get(),Read(build/(std::string(n)+".dxil")));};
  auto pActivation=make("output_head_full_activation_d3d12"),pHidden=make("output_head_full_first128_hidden_d3d12"),pFirst=make("output_head_full_first128_project_d3d12"),pMma=make("output_head_full_mma128_175_d3d12"),pPrepQk=make("output_head_full_prepare_qk_d3d12"),pPrepV=make("output_head_full_prepare_v_d3d12"),pQk=make("output_head_full_qk_d3d12"),pSoft=make("output_head_full_softmax_v_d3d12"),pFinal=make("output_head_final_projection_d3d12"),pTail=make("output_head_tail_d3d12"),pSurface=make("output_head_surface_d3d12");
  auto uMain=Upload(device.Get(),mainFeature),uSkip=Upload(device.Get(),skipFeature),uHead=Upload(device.Get(),head),uBase=Upload(device.Get(),base);
  auto fusedE4=DefaultBuffer(device.Get(),kFullFusedE4Bytes),fusedHalf=DefaultBuffer(device.Get(),kProjectedBytes),hidden=DefaultBuffer(device.Get(),kFullHiddenBytes),first=DefaultBuffer(device.Get(),kProjectedBytes),projection=DefaultBuffer(device.Get(),kFullProjectionBytes),q=DefaultBuffer(device.Get(),kFullQkvBytes),k=DefaultBuffer(device.Get(),kFullQkvBytes),v=DefaultBuffer(device.Get(),kFullQkvBytes),qk=DefaultBuffer(device.Get(),kFullQkBytes),attention=DefaultBuffer(device.Get(),kProjectedBytes),projected=DefaultBuffer(device.Get(),kProjectedBytes),residual=DefaultBuffer(device.Get(),kResidualBytes),surface=DefaultBuffer(device.Get(),kSurfaceBytes);
  auto rf=Readback(device.Get(),kProjectedBytes),rp=Readback(device.Get(),kFullProjectionBytes),rqk=Readback(device.Get(),kFullQkBytes),ra=Readback(device.Get(),kProjectedBytes),rap=Readback(device.Get(),kProjectedBytes),rr=Readback(device.Get(),kResidualBytes),rs=Readback(device.Get(),kSurfaceBytes);
  D3D12_COMMAND_QUEUE_DESC qd{};qd.Type=D3D12_COMMAND_LIST_TYPE_DIRECT;ComPtr<ID3D12CommandQueue> queue;HR_CHECK(device->CreateCommandQueue(&qd,IID_PPV_ARGS(&queue)));ComPtr<ID3D12CommandAllocator> allocator;HR_CHECK(device->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT,IID_PPV_ARGS(&allocator)));ComPtr<ID3D12GraphicsCommandList> list;HR_CHECK(device->CreateCommandList(0,D3D12_COMMAND_LIST_TYPE_DIRECT,allocator.Get(),pActivation.Get(),IID_PPV_ARGS(&list)));list->SetComputeRootSignature(root.Get());
  Bind(list.Get(),pActivation.Get(),uMain.Get(),uSkip.Get(),uHead.Get(),fusedE4.Get(),fusedHalf.Get());list->Dispatch(uint32_t((kFullFusedE4Bytes/4+255)/256),1,1);Transition(list.Get(),fusedE4.Get(),D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);Transition(list.Get(),fusedHalf.Get(),D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);
  Bind(list.Get(),pHidden.Get(),fusedE4.Get(),uHead.Get(),nullptr,hidden.Get());list->Dispatch(uint32_t((kFullHiddenBytes/4+255)/256),1,1);Transition(list.Get(),hidden.Get(),D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);
  Bind(list.Get(),pFirst.Get(),fusedHalf.Get(),hidden.Get(),uHead.Get(),first.Get());list->Dispatch(uint32_t((kProjectedBytes/4+255)/256),1,1);Transition(list.Get(),first.Get(),D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);
  Bind(list.Get(),pMma.Get(),first.Get(),uHead.Get(),nullptr,projection.Get());list->Dispatch(uint32_t((kFullProjectionBytes/4+255)/256),1,1);Transition(list.Get(),projection.Get(),D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);
  Bind(list.Get(),pPrepQk.Get(),projection.Get(),uHead.Get(),nullptr,q.Get(),k.Get());list->Dispatch((kWorkItems+63)/64,1,1);Transition(list.Get(),q.Get(),D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);Transition(list.Get(),k.Get(),D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);
  Bind(list.Get(),pPrepV.Get(),projection.Get(),nullptr,nullptr,v.Get());list->Dispatch(uint32_t((kFullQkvBytes/4+255)/256),1,1);Transition(list.Get(),v.Get(),D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);
  Bind(list.Get(),pQk.Get(),q.Get(),k.Get(),uHead.Get(),qk.Get());list->Dispatch(uint32_t((kFullQkBytes/4+255)/256),1,1);Transition(list.Get(),qk.Get(),D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);
  Bind(list.Get(),pSoft.Get(),qk.Get(),v.Get(),nullptr,attention.Get());list->Dispatch((kWorkItems+63)/64,1,1);Transition(list.Get(),attention.Get(),D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);
  Bind(list.Get(),pFinal.Get(),attention.Get(),first.Get(),uHead.Get(),projected.Get());list->Dispatch((kWorkItems*32+255)/256,1,1);Transition(list.Get(),projected.Get(),D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);
  Bind(list.Get(),pTail.Get(),projected.Get(),uHead.Get(),nullptr,residual.Get());list->Dispatch((kWorkItems+255)/256,1,1);Transition(list.Get(),residual.Get(),D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);
  Bind(list.Get(),pSurface.Get(),residual.Get(),uBase.Get(),nullptr,surface.Get());list->Dispatch((kWorkItems+255)/256,1,1);
  auto copy=[&](ID3D12Resource* src,D3D12_RESOURCE_STATES state,ID3D12Resource* dst,uint64_t bytes){Transition(list.Get(),src,state,D3D12_RESOURCE_STATE_COPY_SOURCE);list->CopyBufferRegion(dst,0,src,0,bytes);};
  copy(first.Get(),D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,rf.Get(),kProjectedBytes);copy(projection.Get(),D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,rp.Get(),kFullProjectionBytes);copy(qk.Get(),D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,rqk.Get(),kFullQkBytes);copy(attention.Get(),D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,ra.Get(),kProjectedBytes);copy(projected.Get(),D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,rap.Get(),kProjectedBytes);copy(residual.Get(),D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,rr.Get(),kResidualBytes);copy(surface.Get(),D3D12_RESOURCE_STATE_UNORDERED_ACCESS,rs.Get(),kSurfaceBytes);
  HR_CHECK(list->Close());ID3D12CommandList* lists[]={list.Get()};queue->ExecuteCommandLists(1,lists);ComPtr<ID3D12Fence> fence;HR_CHECK(device->CreateFence(0,D3D12_FENCE_FLAG_NONE,IID_PPV_ARGS(&fence)));HR_CHECK(queue->Signal(fence.Get(),1));HANDLE event=CreateEventW(nullptr,FALSE,FALSE,nullptr);if(!event)throw std::runtime_error("CreateEvent failed");if(fence->GetCompletedValue()<1){HR_CHECK(fence->SetEventOnCompletion(1,event));WaitForSingleObject(event,INFINITE);}CloseHandle(event);
  auto af=GetReadback(rf.Get(),kProjectedBytes),ap=GetReadback(rp.Get(),kFullProjectionBytes),aqk=GetReadback(rqk.Get(),kFullQkBytes),aa=GetReadback(ra.Get(),kProjectedBytes),aap=GetReadback(rap.Get(),kProjectedBytes),ar=GetReadback(rr.Get(),kResidualBytes),as=GetReadback(rs.Get(),kSurfaceBytes);
  auto mf=CompareFull(af,ef),mp=CompareFull(ap,ep),mqk=CompareFull(aqk,eqk),ma=CompareFull(aa,ea),map=CompareFull(aap,eap),mr=CompareFull(ar,er),ms=CompareFull(as,es);uint64_t nf=mf.nonFinite+mp.nonFinite+mqk.nonFinite+ma.nonFinite+map.nonFinite+mr.nonFinite+ms.nonFinite;
  bool pass=nf==0&&ms.mean<=0.001&&ms.maximum<=0.01f;Write(argv[11],as.data(),as.size());
  auto item=[&](const char* n,const FullMetrics& m,uint64_t bytes){return std::string("  \"")+n+"\": {\"half_mismatches\": "+std::to_string(m.mismatches)+", \"mismatch_ratio\": "+FormatNumber(double(m.mismatches)/double(bytes/2))+", \"mean_absolute_error\": "+FormatNumber(m.mean)+", \"max_absolute_error\": "+FormatNumber(m.maximum)+"}";};
  std::string manifest="{\n  \"schema\": 1,\n  \"experiment\": \"output_head_full_d3d12\",\n  \"status\": \""+std::string(pass?"PASS":"FAIL")+"\",\n  \"classification\": \"SAME_COMMAND_LIST_D3D12_COMPLETE_OUTPUT_HEAD\",\n  \"d3d12_vendor_id\": \"0x1002\",\n  \"dispatches\": 11,\n  \"single_command_list\": true,\n  \"original_weights\": true,\n  \"hip_runtime_dependency\": false,\n  \"checkpoints\": {\n"+item("first128",mf,kProjectedBytes)+",\n"+item("mma128_175",mp,kFullProjectionBytes)+",\n"+item("qk",mqk,kFullQkBytes)+",\n"+item("attention",ma,kProjectedBytes)+",\n"+item("final_projection",map,kProjectedBytes)+",\n"+item("residual",mr,kResidualBytes)+",\n"+item("surface",ms,kSurfaceBytes)+"\n  },\n  \"non_finite_values\": "+std::to_string(nf)+",\n  \"game_runtime_ready\": false,\n  \"next_gate\": \"Bind the complete output head to live slot-154 D3D12 resources\"\n}\n";Write(argv[12],manifest.data(),manifest.size());
  std::printf("[%s] full D3D12 output head: first=%llu projection=%llu qk=%llu attention=%llu surface=%llu mean/max=%g/%g\n",pass?"PASS":"FAIL",(unsigned long long)mf.mismatches,(unsigned long long)mp.mismatches,(unsigned long long)mqk.mismatches,(unsigned long long)ma.mismatches,(unsigned long long)ms.mismatches,ms.mean,ms.maximum);return pass?0:1;
}catch(const std::exception& e){std::fprintf(stderr,"ERROR: %s\n",e.what());return 1;}}
