#define OUTPUT_HEAD_RECORDING_HELPERS_ONLY
#include "../output_head_surface_d3d12/output_head_recording_selftest.cpp"
#include "present_surface.h"
#include "ffx_observer.h"
#include "capture_session.h"

static void Wait(ID3D12Device* d,ID3D12CommandQueue* q){ComPtr<ID3D12Fence> f;HR_CHECK(d->CreateFence(0,D3D12_FENCE_FLAG_NONE,IID_PPV_ARGS(&f)));HR_CHECK(q->Signal(f.Get(),1));HANDLE e=CreateEventW(nullptr,FALSE,FALSE,nullptr);if(!e||FAILED(f->SetEventOnCompletion(1,e))||WaitForSingleObject(e,2000)!=WAIT_OBJECT_0)TerminateProcess(GetCurrentProcess(),3);CloseHandle(e);HR_CHECK(d->GetDeviceRemovedReason());}
static std::vector<uint8_t> Pixels(ID3D12Device* d,ID3D12CommandQueue* q,ID3D12Resource* t){
    auto td=t->GetDesc();D3D12_PLACED_SUBRESOURCE_FOOTPRINT fp{};UINT rows;UINT64 rb,total;d->GetCopyableFootprints(&td,0,1,0,&fp,&rows,&rb,&total);auto down=Readback(d,total);ComPtr<ID3D12CommandAllocator> a;ComPtr<ID3D12GraphicsCommandList> l;HR_CHECK(d->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT,IID_PPV_ARGS(&a)));HR_CHECK(d->CreateCommandList(0,D3D12_COMMAND_LIST_TYPE_DIRECT,a.Get(),nullptr,IID_PPV_ARGS(&l)));
    Recorder::Transition(l.Get(),t,D3D12_RESOURCE_STATE_PRESENT,D3D12_RESOURCE_STATE_COPY_SOURCE);auto src=Recorder::TextureLocation(t);D3D12_TEXTURE_COPY_LOCATION dst{};dst.pResource=down.Get();dst.Type=D3D12_TEXTURE_COPY_TYPE_PLACED_FOOTPRINT;dst.PlacedFootprint=fp;l->CopyTextureRegion(&dst,0,0,0,&src,nullptr);Recorder::Transition(l.Get(),t,D3D12_RESOURCE_STATE_COPY_SOURCE,D3D12_RESOURCE_STATE_PRESENT);HR_CHECK(l->Close());ID3D12CommandList* lists[]={l.Get()};q->ExecuteCommandLists(1,lists);Wait(d,q);auto packed=ReadGpu(down.Get(),size_t(total));std::vector<uint8_t> raw(size_t(rb)*rows);for(UINT y=0;y<rows;++y)std::memcpy(raw.data()+y*rb,packed.data()+fp.Offset+y*fp.Footprint.RowPitch,size_t(rb));return raw;
}
int wmain(int argc,wchar_t** argv){
    if(argc!=3&&argc!=4)return 2;bool amd=!wcscmp(argv[2],L"--amd"),failure=argc==4&&!wcscmp(argv[3],L"--expect-worker-failure");if((!amd&&wcscmp(argv[2],L"--warp"))||(argc==4&&!failure))return 2;
    auto root=fs::absolute(argv[1]);if(fs::exists(root))return 2;fs::create_directories(root);
    try{
        // All representable packed channels survive half conversion exactly.
        for(auto format:{DXGI_FORMAT_R8G8B8A8_UNORM,DXGI_FORMAT_B8G8R8A8_UNORM,DXGI_FORMAT_R10G10B10A2_UNORM}){
            std::vector<uint8_t> test(4096*4);for(uint32_t i=0;i<4096;++i){uint32_t p=i*0x1020401u;std::memcpy(test.data()+i*4,&p,4);}if(nr_present::Encode(nr_present::Decode(test,format),test,format)!=test)throw std::runtime_error("packed half roundtrip");}
        wchar_t exe[32768]{};GetModuleFileNameW(nullptr,exe,32768);auto bin=fs::path(exe).parent_path();auto dll=LoadLibraryExW((bin/L"resident_present.dll").c_str(),nullptr,LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR|LOAD_LIBRARY_SEARCH_SYSTEM32);if(!dll)throw std::runtime_error("present DLL");using Entry=DWORD(WINAPI*)(void*);auto init=reinterpret_cast<Entry>(GetProcAddress(dll,"FfxObserver_Bootstrap")),control=reinterpret_cast<Entry>(GetProcAddress(dll,"FfxSession_Command"));if(!init||!control)throw std::runtime_error("exports");
        ComPtr<ID3D12Debug> debug;HR_CHECK(D3D12GetDebugInterface(IID_PPV_ARGS(&debug)));debug->EnableDebugLayer();
        FfxObserverBootstrapV2 cfg{};cfg.size=sizeof(cfg);cfg.version=2;cfg.event_limit=1000;wcscpy_s(cfg.log_path,(root/L"events.jsonl").c_str());if(init(&cfg)!=1)throw std::runtime_error("bootstrap");
        ComPtr<IDXGIFactory6> factory;HR_CHECK(CreateDXGIFactory1(IID_PPV_ARGS(&factory)));ComPtr<IDXGIAdapter1> adapter;DXGI_ADAPTER_DESC1 ad{};if(amd){bool found=false;for(UINT i=0;factory->EnumAdapters1(i,&adapter)!=DXGI_ERROR_NOT_FOUND;++i,adapter.Reset()){adapter->GetDesc1(&ad);if(ad.VendorId==0x1002&&!(ad.Flags&DXGI_ADAPTER_FLAG_SOFTWARE)){found=true;break;}}if(!found)throw std::runtime_error("AMD missing");}else{HR_CHECK(factory->EnumWarpAdapter(IID_PPV_ARGS(&adapter)));adapter->GetDesc1(&ad);}
        ComPtr<ID3D12Device> d;HR_CHECK(D3D12CreateDevice(adapter.Get(),D3D_FEATURE_LEVEL_12_0,IID_PPV_ARGS(&d)));ComPtr<ID3D12InfoQueue> info;HR_CHECK(d.As(&info));D3D12_COMMAND_QUEUE_DESC qd{};ComPtr<ID3D12CommandQueue> q;HR_CHECK(d->CreateCommandQueue(&qd,IID_PPV_ARGS(&q)));
        WNDCLASSW wc{};wc.lpfnWndProc=DefWindowProcW;wc.hInstance=GetModuleHandleW(nullptr);wc.lpszClassName=L"NRPresentIsolatedTest";if(!RegisterClassW(&wc))throw std::runtime_error("test class");HWND hwnd=CreateWindowExW(0,wc.lpszClassName,L"Isolated original-network presentation test",WS_OVERLAPPEDWINDOW,0,0,680,410,nullptr,nullptr,wc.hInstance,nullptr);if(!hwnd)throw std::runtime_error("test window");ShowWindow(hwnd,SW_SHOWNOACTIVATE);
        DXGI_SWAP_CHAIN_DESC1 sd{};sd.Width=640;sd.Height=360;sd.Format=DXGI_FORMAT_R8G8B8A8_UNORM;sd.SampleDesc.Count=1;sd.BufferUsage=DXGI_USAGE_RENDER_TARGET_OUTPUT;sd.BufferCount=2;sd.SwapEffect=DXGI_SWAP_EFFECT_FLIP_DISCARD;ComPtr<IDXGISwapChain1> initial;HR_CHECK(factory->CreateSwapChainForHwnd(q.Get(),hwnd,&sd,nullptr,nullptr,&initial));ComPtr<IDXGISwapChain3> swap;HR_CHECK(initial.As(&swap));HR_CHECK(swap->SetColorSpace1(DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709));
        D3D12_DESCRIPTOR_HEAP_DESC hd{};hd.Type=D3D12_DESCRIPTOR_HEAP_TYPE_RTV;hd.NumDescriptors=1;ComPtr<ID3D12DescriptorHeap> heap;HR_CHECK(d->CreateDescriptorHeap(&hd,IID_PPV_ARGS(&heap)));auto rtv=heap->GetCPUDescriptorHandleForHeapStart();bool exact=true,changed=false;
        FfxSessionCommandV1 command{sizeof(command),19};if(control(&command)!=1)throw std::runtime_error("start");
        for(UINT i=0;i<3;++i){MSG m;while(PeekMessageW(&m,nullptr,0,0,PM_REMOVE)){TranslateMessage(&m);DispatchMessageW(&m);}if(i==2){command.command=20;if(control(&command)!=1)throw std::runtime_error("stop");}
            ComPtr<ID3D12Resource> target;HR_CHECK(swap->GetBuffer(swap->GetCurrentBackBufferIndex(),IID_PPV_ARGS(&target)));d->CreateRenderTargetView(target.Get(),nullptr,rtv);ComPtr<ID3D12CommandAllocator> a;ComPtr<ID3D12GraphicsCommandList> l;HR_CHECK(d->CreateCommandAllocator(qd.Type,IID_PPV_ARGS(&a)));HR_CHECK(d->CreateCommandList(0,qd.Type,a.Get(),nullptr,IID_PPV_ARGS(&l)));Recorder::Transition(l.Get(),target.Get(),D3D12_RESOURCE_STATE_PRESENT,D3D12_RESOURCE_STATE_RENDER_TARGET);float color[]={.15f+.12f*i,.25f,.65f-.08f*i,1};l->ClearRenderTargetView(rtv,color,0,nullptr);Recorder::Transition(l.Get(),target.Get(),D3D12_RESOURCE_STATE_RENDER_TARGET,D3D12_RESOURCE_STATE_PRESENT);HR_CHECK(l->Close());ID3D12CommandList* lists[]={l.Get()};q->ExecuteCommandLists(1,lists);Wait(d.Get(),q.Get());auto before=Pixels(d.Get(),q.Get(),target.Get());
            HR_CHECK(swap->Present(0,DXGI_PRESENT_TEST)); // probe must not infer
            HRESULT present;if(i==1){DXGI_PRESENT_PARAMETERS p{};present=swap->Present1(0,0,&p);}else present=swap->Present(0,0);if(present!=S_OK)throw std::runtime_error("test Present not accepted");auto after=Pixels(d.Get(),q.Get(),target.Get());
            if(i<2&&!failure){auto result=Read(root/L"present_frames"/(L"encoded_output"+std::to_wstring(i+1)+L".raw"));auto input=Read(root/L"present_frames"/(L"encoded_input"+std::to_wstring(i+1)+L".raw"));exact&=after==result&&before==input;changed|=after!=before;}else exact&=after==before;
            Write(root/(L"display_buffer"+std::to_wstring(i)+L".raw"),after.data(),after.size());
        }
        Wait(d.Get(),q.Get());HR_CHECK(swap->ResizeBuffers(2,641,361,DXGI_FORMAT_R8G8B8A8_UNORM,0));command.command=21;if(control(&command)!=1)throw std::runtime_error("status");DestroyWindow(hwnd);
        UINT errors=0,warnings=0;for(UINT64 i=0;i<info->GetNumStoredMessages();++i){SIZE_T n=0;info->GetMessage(i,nullptr,&n);std::vector<uint8_t> b(n);auto* m=reinterpret_cast<D3D12_MESSAGE*>(b.data());info->GetMessage(i,m,&n);errors+=m->Severity<=D3D12_MESSAGE_SEVERITY_ERROR;warnings+=m->Severity==D3D12_MESSAGE_SEVERITY_WARNING;if(m->Severity<=D3D12_MESSAGE_SEVERITY_WARNING)std::fprintf(stderr,"%s\n",m->pDescription);}
        bool pass=exact&&(changed||failure)&&!errors&&!warnings;std::ostringstream report;report<<"{\"status\":\""<<(pass?"PASS":"FAIL")<<"\",\"adapter_vendor\":"<<ad.VendorId<<",\"expected_worker_failure\":"<<(failure?"true":"false")<<",\"presented_buffer_exact\":"<<(exact?"true":"false")<<",\"stop_baseline_exact\":"<<(exact?"true":"false")<<",\"nonidentity\":"<<(changed?"true":"false")<<",\"resize_after_release\":true,\"d3d12_errors\":"<<errors<<",\"d3d12_warnings\":"<<warnings<<"}\n";auto text=report.str();Write(root/L"summary.json",text.data(),text.size());std::printf("%s",text.c_str());return pass?0:1;
    }catch(const std::exception& e){std::fprintf(stderr,"present test: %s\n",e.what());return 1;}
}
