[CmdletBinding()]
param([string]$TraceRoot='results\20260904_100000_n0_normal0_boundary_full_grid_trace')
$ErrorActionPreference='Stop';$repo=Split-Path -Parent $PSScriptRoot
& (Join-Path $PSScriptRoot 'build_all.ps1') -Only zluda_ptx_probe;if($LASTEXITCODE-ne 0){throw'probe build failed'}
$root=if([IO.Path]::IsPathRooted($TraceRoot)){(Resolve-Path -LiteralPath $TraceRoot).Path}else{(Resolve-Path -LiteralPath (Join-Path $repo $TraceRoot)).Path};$inst=Get-Content -Raw -LiteralPath (Join-Path $root 'instrumentation_rtx.json')|ConvertFrom-Json
$stamp=Get-Date -Format yyyyMMdd_HHmmss;$stage=Join-Path $repo "deliverables\n0_normal0_boundary_full_grid_trace_reference_$stamp";$payload=Join-Path $stage payload;$scripts=Join-Path $stage scripts;New-Item -ItemType Directory -Path $payload,$scripts|Out-Null
Copy-Item -LiteralPath (Join-Path $repo 'build\zluda_ptx_probe.exe') -Destination (Join-Path $payload 'neural_reference_probe.exe')
$sources=[ordered]@{'n0_boundary_trace.ptx'=(Join-Path $root 'n0_boundary_trace_original.ptx');'n0_original.ptx'=(Join-Path $repo 'results\20260831_011219_zluda_ptx_probe\neural_isolated.ptx')};foreach($pair in $sources.GetEnumerator()){$text=[IO.File]::ReadAllText($pair.Value);$normalized=$text-replace'(?m)^\.version 9\.4$','.version 8.7';if($normalized-eq$text){throw"PTX version not found: $($pair.Value)"};[IO.File]::WriteAllText((Join-Path $payload $pair.Key),$normalized,[Text.UTF8Encoding]::new($false))}
Copy-Item -LiteralPath (Join-Path $repo 'results\20260901_153000_n0_zero_input\input_rgba16f_zero.raw') -Destination (Join-Path $payload 'input_rgba16f.raw');$base=Join-Path $repo 'deliverables\n0_full_reference_20260831_130219\payload';Copy-Item -LiteralPath (Join-Path $base 'weights.raw'),(Join-Path $base 'params.raw') -Destination $payload;Copy-Item -LiteralPath (Join-Path $PSScriptRoot 'run_nvidia_n0_normal0_boundary_full_grid_trace.ps1') -Destination $scripts;Copy-Item -LiteralPath (Join-Path $repo 'N0_NORMAL0_BOUNDARY_FULL_GRID_REFERENCE_README.md') -Destination (Join-Path $stage 'README.md')
$req=@('neural_reference_probe.exe','n0_boundary_trace.ptx','n0_original.ptx','input_rgba16f.raw','weights.raw','params.raw');$hashes=[ordered]@{};foreach($name in $req){$hashes[$name]=(Get-FileHash -LiteralPath (Join-Path $payload $name)).Hash};[ordered]@{schema=1;experiment='rtx_n0_normal0_boundary_full_grid_trace_package';function='cc_tinlayout_fused_pre_block_swin_1h_32_1_ds_fp8';grid=$inst.grid;block=$inst.block;sample_count=[int]$inst.sample_count;bytes_per_sample=[int]$inst.bytes_per_sample;fields=$inst.fields;trace_offset=[int64]$inst.trace_offset;trace_bytes=[int]$inst.trace_bytes;scratch_extra_bytes=[int]$inst.scratch_extra_bytes;payload_sha256=$hashes}|ConvertTo-Json -Depth 8|Set-Content -LiteralPath (Join-Path $stage 'manifest.json') -Encoding utf8
$zip="$stage.zip";Compress-Archive -LiteralPath $stage -DestinationPath $zip -CompressionLevel Optimal;Write-Host "Package: $zip";Write-Host "SHA256: $((Get-FileHash -LiteralPath $zip).Hash)"
