[CmdletBinding()]
param([string]$PackageRoot)
$ErrorActionPreference='Stop';$PSNativeCommandUseErrorActionPreference=$false
if([string]::IsNullOrWhiteSpace($PackageRoot)){$PackageRoot=Split-Path -Parent $PSScriptRoot}
$root=(Resolve-Path -LiteralPath $PackageRoot).Path;$payload=Join-Path $root payload;$pm=Get-Content -Raw -LiteralPath (Join-Path $root manifest.json)|ConvertFrom-Json
$nvcuda=Join-Path $env:WINDIR 'System32\nvcuda.dll';if(-not(Test-Path -LiteralPath $nvcuda)){throw"NVIDIA driver not found: $nvcuda"}
$required=@('neural_reference_probe.exe','n0_box_outputs_trace.ptx','n0_mma_trace.ptx','n0_original.ptx','input_rgba16f.raw','weights.raw','params.raw');$actual=[ordered]@{};$integrity=$true
foreach($name in $required){$path=Join-Path $payload $name;if(-not(Test-Path -LiteralPath $path)){throw"Missing payload: $name"};$actual[$name]=(Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash;$integrity=$integrity-and$actual[$name]-eq$pm.payload_sha256.$name}
$x=[int]$pm.target_cta[0];$y=[int]$pm.target_cta[1];$stamp=Get-Date -Format yyyyMMdd_HHmmss;$work=Join-Path $root "_n0_cta${x}_${y}_residual_bundle_work_$stamp";$result=Join-Path $root "_n0_cta${x}_${y}_residual_bundle_reference_result_$stamp";New-Item -ItemType Directory -Path $work,$result|Out-Null
$cases=@([pscustomobject]@{name='box_outputs';ptx='n0_box_outputs_trace.ptx';meta=$pm.box_outputs},[pscustomobject]@{name='mma';ptx='n0_mma_trace.ptx';meta=$pm.mma});$caseResults=@()
foreach($case in $cases){$json=Join-Path $work "$($case.name)_probe.json";$scratch=Join-Path $work "$($case.name)_scratch.raw";$output=Join-Path $work "$($case.name)_output.raw";$log=Join-Path $work "$($case.name)_stdout.log"
& (Join-Path $payload neural_reference_probe.exe) --nvcuda $nvcuda --ptx (Join-Path $payload $case.ptx) --function $pm.function --json $json --n0-input (Join-Path $payload input_rgba16f.raw) --n0-weights (Join-Path $payload weights.raw) --n0-params (Join-Path $payload params.raw) --n0-scratch-out $scratch --n0-output $output --n0-grid-x 80 --n0-grid-y 48 --n0-scratch-extra-bytes ([int]$case.meta.scratch_extra_bytes) *> $log
$exit=$LASTEXITCODE;$probe=if(Test-Path -LiteralPath $json){Get-Content -Raw -LiteralPath $json|ConvertFrom-Json}else{$null};$trace=Join-Path $result "$($case.name)_trace.raw";$traceBytes=[int]$case.meta.trace_bytes;$stream=[IO.File]::OpenRead($scratch);try{[void]$stream.Seek([int64]$case.meta.trace_offset,[IO.SeekOrigin]::Begin);$buffer=[byte[]]::new($traceBytes);$read=0;while($read-lt$traceBytes){$count=$stream.Read($buffer,$read,$traceBytes-$read);if($count-eq 0){break};$read+=$count};if($read-ne$traceBytes){throw"Trace extraction short read: $read/$traceBytes"};[IO.File]::WriteAllBytes($trace,$buffer)}finally{$stream.Dispose()};Copy-Item -LiteralPath $json,$log -Destination $result
$caseResults+=[ordered]@{name=$case.name;probe_exit=$exit;probe_pass=[bool]($probe-and$probe.pass);execution_verified=[bool]($probe-and$probe.execution_verified);output_sha256=(Get-FileHash -LiteralPath $output -Algorithm SHA256).Hash;trace_bytes=$traceBytes;trace_sha256=(Get-FileHash -LiteralPath $trace -Algorithm SHA256).Hash;trace_nonzero_bytes=@([IO.File]::ReadAllBytes($trace)|Where-Object{$_-ne 0}).Count}}
$baseJson=Join-Path $work baseline_probe.json;$baseScratch=Join-Path $work baseline_scratch.raw;$baseOutput=Join-Path $work baseline_output.raw;$baseLog=Join-Path $work baseline_stdout.log
& (Join-Path $payload neural_reference_probe.exe) --nvcuda $nvcuda --ptx (Join-Path $payload n0_original.ptx) --function $pm.function --json $baseJson --n0-input (Join-Path $payload input_rgba16f.raw) --n0-weights (Join-Path $payload weights.raw) --n0-params (Join-Path $payload params.raw) --n0-scratch-out $baseScratch --n0-output $baseOutput --n0-grid-x 80 --n0-grid-y 48 *> $baseLog
$baseExit=$LASTEXITCODE;$baseProbe=if(Test-Path -LiteralPath $baseJson){Get-Content -Raw -LiteralPath $baseJson|ConvertFrom-Json}else{$null};$baseHash=if(Test-Path -LiteralPath $baseOutput){(Get-FileHash -LiteralPath $baseOutput -Algorithm SHA256).Hash}else{$null};Copy-Item -LiteralPath $baseJson,$baseLog -Destination $result
$preserved=$true;$runsPass=$true;foreach($case in $caseResults){$preserved=$preserved-and$case.output_sha256-eq$baseHash;$runsPass=$runsPass-and$case.probe_exit-eq 0-and$case.probe_pass-and$case.execution_verified-and$case.trace_nonzero_bytes-gt 0}
$pass=$integrity-and$runsPass-and$baseExit-eq 0-and$baseProbe-and$baseProbe.pass-and$baseProbe.execution_verified-and$preserved
[ordered]@{schema=1;experiment='rtx_n0_selected_cta_residual_bundle';status=if($pass){'PASS'}else{'FAIL'};classification='RTX_N0_RESIDUAL_BOX_BOUNDARY_AND_ALL_MMA_ORACLE';counts_as_s7=$false;payload_integrity=$integrity;payload_sha256=$actual;device_name=if($baseProbe){$baseProbe.device_name}else{$null};grid=@(80,48,1);block=@(32,1,1);target_cta=$pm.target_cta;baseline_probe_exit=$baseExit;baseline_probe_pass=[bool]($baseProbe-and$baseProbe.pass);baseline_output_sha256=$baseHash;reference_outputs_preserved=[bool]$preserved;cases=$caseResults}|ConvertTo-Json -Depth 8|Set-Content -LiteralPath (Join-Path $result manifest.json) -Encoding utf8
$zip="$result.zip";Compress-Archive -LiteralPath $result -DestinationPath $zip -CompressionLevel Optimal;Get-Content -Raw -LiteralPath (Join-Path $result manifest.json);Write-Host "Result: $zip";exit $(if($pass){0}else{1})
