[CmdletBinding()]
param([string]$PackageRoot)
$ErrorActionPreference='Stop';$PSNativeCommandUseErrorActionPreference=$false
if([string]::IsNullOrWhiteSpace($PackageRoot)){$PackageRoot=Split-Path -Parent $PSScriptRoot}
$root=(Resolve-Path $PackageRoot).Path;$payload=Join-Path $root 'payload';$pm=Get-Content -Raw (Join-Path $root 'manifest.json')|ConvertFrom-Json;$nvcuda=Join-Path $env:WINDIR 'System32\nvcuda.dll';if(-not(Test-Path $nvcuda)){throw"NVIDIA driver not found: $nvcuda"}
$req=@('neural_reference_probe.exe','n0_cos_trace.ptx','n0_original.ptx','input_rgba16f.raw','weights.raw','params.raw');$actual=[ordered]@{};$integrity=$true;foreach($f in $req){$p=Join-Path $payload $f;if(-not(Test-Path $p)){throw"Missing payload: $f"};$actual[$f]=(Get-FileHash $p).Hash;$integrity=$integrity-and$actual[$f]-eq$pm.payload_sha256.$f}
$stamp=Get-Date -Format yyyyMMdd_HHmmss;$work=Join-Path $root "_n0_cos_full_grid_trace_work_$stamp";$result=Join-Path $root "_n0_cos_full_grid_trace_reference_result_$stamp";New-Item -ItemType Directory -Path $work,$result|Out-Null
function Run($ptx,$tag,[int]$extra){$json=Join-Path $work "$tag.json";$scratch=Join-Path $work "$tag.scratch.raw";$output=Join-Path $work "$tag.output.raw";$args=@('--nvcuda',$nvcuda,'--ptx',$ptx,'--function',$pm.function,'--json',$json,'--n0-input',(Join-Path $payload 'input_rgba16f.raw'),'--n0-weights',(Join-Path $payload 'weights.raw'),'--n0-params',(Join-Path $payload 'params.raw'),'--n0-scratch-out',$scratch,'--n0-output',$output,'--n0-grid-x','80','--n0-grid-y','48');if($extra-gt 0){$args+=@('--n0-scratch-extra-bytes',[string]$extra)};&(Join-Path $payload 'neural_reference_probe.exe') @args *> (Join-Path $work "$tag.log");[ordered]@{exit=$LASTEXITCODE;json=$json;scratch=$scratch;output=$output}}
$base=Run (Join-Path $payload 'n0_original.ptx') 'baseline' 0;$bp=Get-Content -Raw $base.json|ConvertFrom-Json;$run=Run (Join-Path $payload 'n0_cos_trace.ptx') 'cos' ([int]$pm.scratch_extra_bytes);$probe=Get-Content -Raw $run.json|ConvertFrom-Json
$stream=[IO.File]::OpenRead($run.scratch);try{[void]$stream.Seek([int64]$pm.trace_offset,[IO.SeekOrigin]::Begin);$buf=[byte[]]::new([int]$pm.trace_bytes);$read=0;while($read-lt$buf.Length){$n=$stream.Read($buf,$read,$buf.Length-$read);if($n-eq 0){break};$read+=$n};if($read-ne$buf.Length){throw"short trace: $read"}}finally{$stream.Dispose()};$trace=Join-Path $result 'cos_trace.raw';[IO.File]::WriteAllBytes($trace,$buf)
$baseHash=(Get-FileHash $base.output).Hash;$outputHash=(Get-FileHash $run.output).Hash;$preserved=$outputHash-eq$baseHash;$pass=$integrity-and$base.exit-eq 0-and$bp.pass-and$run.exit-eq 0-and$probe.pass-and$probe.execution_verified-and$preserved
[ordered]@{schema=1;experiment='rtx_n0_cos_full_grid_trace';status=if($pass){'PASS'}else{'FAIL'};classification='CONTROLLED_COS_INPUT_OUTPUT_CURVE_DATASET';counts_as_s7=$false;payload_integrity=$integrity;device_name=$probe.device_name;grid=$pm.grid;block=$pm.block;kernel_launched=[bool]$probe.kernel_launched;sample_count=[int]$pm.sample_count;bytes_per_sample=[int]$pm.bytes_per_sample;checkpoint_bytes=[int]$pm.trace_bytes;checkpoint_sha256=(Get-FileHash $trace).Hash;output_sha256=$outputHash;baseline_output_sha256=$baseHash;reference_output_preserved=$preserved;instrumentation_perturbed=(-not$preserved)}|ConvertTo-Json -Depth 8|Set-Content (Join-Path $result 'manifest.json') -Encoding utf8
$zip="$result.zip";Compress-Archive $result $zip -CompressionLevel Optimal;Get-Content -Raw (Join-Path $result 'manifest.json');Write-Host "Result: $zip";exit $(if($pass){0}else{1})
