[CmdletBinding()]
param([string]$PackageRoot)
$ErrorActionPreference='Stop';$PSNativeCommandUseErrorActionPreference=$false;if([string]::IsNullOrWhiteSpace($PackageRoot)){$PackageRoot=Split-Path -Parent $PSScriptRoot};$root=(Resolve-Path $PackageRoot).Path;$payload=Join-Path $root 'payload';$pm=Get-Content -Raw (Join-Path $root 'manifest.json')|ConvertFrom-Json;$nvcuda=Join-Path $env:WINDIR 'System32\nvcuda.dll';if(-not(Test-Path $nvcuda)){throw"NVIDIA driver not found: $nvcuda"}
$req=@('neural_reference_probe.exe','n0_lg2_trace.ptx','n0_original.ptx','input_rgba16f.raw','weights.raw','params.raw');$actual=[ordered]@{};$integrity=$true;foreach($f in $req){$p=Join-Path $payload $f;if(-not(Test-Path $p)){throw"Missing payload: $f"};$actual[$f]=(Get-FileHash $p -Algorithm SHA256).Hash;$integrity=$integrity-and$actual[$f]-eq$pm.payload_sha256.$f};$stamp=Get-Date -Format 'yyyyMMdd_HHmmss';$work=Join-Path $root "_n0_lg2_full_grid_trace_work_$stamp";$result=Join-Path $root "_n0_lg2_full_grid_trace_reference_result_$stamp";New-Item -ItemType Directory -Path $work,$result|Out-Null
function Run-Probe($ptx,$json,$scratch,$output,$log,[int]$extra){$a=@('--nvcuda',$nvcuda,'--ptx',$ptx,'--function',$pm.function,'--json',$json,'--n0-input',(Join-Path $payload 'input_rgba16f.raw'),'--n0-weights',(Join-Path $payload 'weights.raw'),'--n0-params',(Join-Path $payload 'params.raw'),'--n0-scratch-out',$scratch,'--n0-output',$output,'--n0-grid-x','80','--n0-grid-y','48');if($extra-gt 0){$a+=@('--n0-scratch-extra-bytes',[string]$extra)};&(Join-Path $payload 'neural_reference_probe.exe') @a *> $log;return $LASTEXITCODE}
$pj=Join-Path $work 'probe.json';$scratch=Join-Path $work 'scratch.raw';$output=Join-Path $work 'output.raw';$probeLog=Join-Path $work 'stdout.log';$pe=Run-Probe (Join-Path $payload 'n0_lg2_trace.ptx') $pj $scratch $output $probeLog ([int]$pm.scratch_extra_bytes)
if($pe-ne 0-or-not(Test-Path $pj)-or-not(Test-Path $scratch)){ $detail=if(Test-Path $probeLog){Get-Content -Raw $probeLog}else{'stdout.log was not created'};throw "Instrumented probe failed (exit=$pe; scratch_exists=$(Test-Path $scratch)). Original probe output:`n$detail" }
$probe=Get-Content -Raw $pj|ConvertFrom-Json;if(-not$probe.pass-or-not$probe.execution_verified){throw "Instrumented probe did not verify execution: $($probe|ConvertTo-Json -Depth 4)"}
$bj=Join-Path $work 'baseline_probe.json';$bs=Join-Path $work 'baseline_scratch.raw';$bo=Join-Path $work 'baseline_output.raw';$baseLog=Join-Path $work 'baseline_stdout.log';$be=Run-Probe (Join-Path $payload 'n0_original.ptx') $bj $bs $bo $baseLog 0
if($be-ne 0-or-not(Test-Path $bj)-or-not(Test-Path $bs)){ $detail=if(Test-Path $baseLog){Get-Content -Raw $baseLog}else{'baseline_stdout.log was not created'};throw "Baseline probe failed (exit=$be). Original probe output:`n$detail" }
$base=Get-Content -Raw $bj|ConvertFrom-Json
$trace=Join-Path $result 'lg2_trace.raw';$stream=[IO.File]::OpenRead($scratch);try{[void]$stream.Seek([int64]$pm.trace_offset,[IO.SeekOrigin]::Begin);$buf=[byte[]]::new([int]$pm.trace_bytes);$read=0;while($read-lt$buf.Length){$n=$stream.Read($buf,$read,$buf.Length-$read);if($n-eq 0){break};$read+=$n};if($read-ne$buf.Length){throw"short trace read: $read"};[IO.File]::WriteAllBytes($trace,$buf)}finally{$stream.Dispose()};$nz=@($buf|Where-Object{$_-ne 0}).Count;$oh=(Get-FileHash $output -Algorithm SHA256).Hash;$bh=(Get-FileHash $bo -Algorithm SHA256).Hash;$preserved=$oh-eq$bh;$pass=$integrity-and$pe-eq 0-and$probe.pass-and$be-eq 0-and$base.pass-and$nz-gt 0;Copy-Item $pj,(Join-Path $work 'stdout.log'),$bj,(Join-Path $work 'baseline_stdout.log') -Destination $result
[ordered]@{schema=1;experiment='rtx_n0_lg2_full_grid_trace';status=if($pass){'PASS'}else{'FAIL'};classification='CONTROLLED_IMMEDIATE_POST_DEFINITION_LG2_CURVE_DATASET';admissible_scope='captured lg2 input/output pairs only; downstream instrumented output excluded';counts_as_s7=$false;payload_integrity=$integrity;payload_sha256=$actual;probe_exit=$pe;probe_pass=[bool]$probe.pass;device_name=$probe.device_name;baseline_probe_exit=$be;baseline_probe_pass=[bool]$base.pass;grid=$pm.grid;block=$pm.block;kernel_launched=[bool]$probe.kernel_launched;sample_count=[int]$pm.sample_count;bytes_per_sample=[int]$pm.bytes_per_sample;checkpoint_bytes=[int]$pm.trace_bytes;checkpoint_nonzero_bytes=$nz;checkpoint_sha256=(Get-FileHash $trace -Algorithm SHA256).Hash;scratch_extra_bytes=[int]$pm.scratch_extra_bytes;input_variant=$pm.input_variant;output_sha256=$oh;baseline_output_sha256=$bh;reference_output_preserved=$preserved;instrumentation_perturbed=(-not$preserved)}|ConvertTo-Json -Depth 8|Set-Content (Join-Path $result 'manifest.json') -Encoding utf8;$zip="$result.zip";Compress-Archive -LiteralPath $result -DestinationPath $zip -CompressionLevel Optimal;Get-Content -Raw (Join-Path $result 'manifest.json');Write-Host "Result: $zip";exit $(if($pass){0}else{1})
