[CmdletBinding()]
param([string]$PackageRoot)
$ErrorActionPreference='Stop';$PSNativeCommandUseErrorActionPreference=$false;$sd=$PSScriptRoot
if([string]::IsNullOrWhiteSpace($sd)){$sd=Split-Path -Parent $MyInvocation.MyCommand.Path};if([string]::IsNullOrWhiteSpace($PackageRoot)){$PackageRoot=Split-Path -Parent $sd}
$root=(Resolve-Path -LiteralPath $PackageRoot).Path;$payload=Join-Path $root 'payload';$pm=Get-Content -Raw -LiteralPath (Join-Path $root 'manifest.json')|ConvertFrom-Json;$nvcuda=Join-Path $env:WINDIR 'System32\nvcuda.dll';if(-not(Test-Path -LiteralPath $nvcuda)){throw "NVIDIA driver not found: $nvcuda"}
$integrity=$true;$hashes=[ordered]@{};foreach($p in $pm.payload_sha256.psobject.Properties){$n=$p.Name;$h=(Get-FileHash -LiteralPath (Join-Path $payload $n) -Algorithm SHA256).Hash;$hashes[$n]=$h;$integrity=$integrity-and$h-eq[string]$p.Value};if(-not$integrity){throw 'payload hash verification failed'}
$stamp=Get-Date -Format 'yyyyMMdd_HHmmss';$result=Join-Path $root "_slot3_f16_reduction_trace_reference_result_$stamp";New-Item -ItemType Directory -Path $result|Out-Null;$arena=Join-Path $result 'arena_after.raw';$output=Join-Path $result 'output.raw';$sync=Join-Path $result 'sync.raw';$probeJson=Join-Path $result 'probe.json'
$args2=@('--nvcuda',$nvcuda,'--ptx',(Join-Path $payload 'slot3_f16_reduction_trace.ptx'),'--function','cc_tinlayout_fused_swin_1h_32_1_chained_fp8','--json',$probeJson,'--n1-arena',(Join-Path $payload 'activation_arena_before.raw'),'--n1-arena-out',$arena,'--n1-arena-input-offset','9940992','--n1-arena-output-offset','11907072','--n1-weights',(Join-Path $payload 'model_arena.raw'),'--n1-params',(Join-Path $payload 'params.raw'),'--n1-output',$output,'--n1-sync-out',$sync,'--n1-input-param-offset','0','--n1-output-param-offset','8','--n1-no-weights-param','--n1-no-release','--n1-expected-releases','0','--n1-grid-x','41','--n1-grid-y','25','--n1-grid-z','1','--n1-block-x','32','--n1-block-y','1','--n1-block-z','1','--n1-arena-param-view','0:9940992','--n1-arena-param-view','8:11907072','--n1-arena-param-view','40:0','--n1-arena-param-view','56:4096','--n1-arena-param-view','64:27807744','--n1-weight-param-view','16:4512256')
& (Join-Path $payload 'neural_reference_probe.exe') @args2 *> (Join-Path $result 'stdout.log');$exitCode=$LASTEXITCODE;$probe=if(Test-Path -LiteralPath $probeJson){Get-Content -Raw -LiteralPath $probeJson|ConvertFrom-Json}else{$null};$checkpoint=Join-Path $result 'f16_reduction_trace.raw'
if(Test-Path -LiteralPath $arena){$buf=New-Object byte[] ([int]$pm.checkpoint_bytes);$s=[IO.File]::OpenRead($arena);try{$null=$s.Seek([int64]$pm.checkpoint_arena_offset,[IO.SeekOrigin]::Begin);$read=$s.Read($buf,0,$buf.Length);if($read-ne$buf.Length){throw "checkpoint short read: $read"}}finally{$s.Dispose()};[IO.File]::WriteAllBytes($checkpoint,$buf)}
$bytes=if(Test-Path $checkpoint){(Get-Item $checkpoint).Length}else{0};$nonzero=if($bytes){([IO.File]::ReadAllBytes($checkpoint)|Where-Object{$_-ne 0}).Count}else{0};$pass=($exitCode-eq 0-and$probe-and$probe.pass-and$probe.device_name-match'NVIDIA'-and$bytes-eq[int64]$pm.checkpoint_bytes-and$nonzero-gt 0)
[ordered]@{schema=1;experiment='rtx5070_slot3_f16_reduction_register_trace';status=if($pass){'PASS'}else{'FAIL'};classification='RTX_PACKED_F16_REDUCTION_ORACLE';counts_as_s7=$false;payload_integrity=$integrity;payload_sha256=$hashes;probe_exit=$exitCode;probe_pass=[bool]($probe-and$probe.pass);device_name=if($probe){$probe.device_name}else{$null};cta=@($pm.cta);registers=@($pm.registers);kernel_launched=[bool]($probe-and$probe.kernel_launched);checkpoint_bytes=$bytes;checkpoint_nonzero_bytes=$nonzero;checkpoint_sha256=if($bytes){(Get-FileHash $checkpoint -Algorithm SHA256).Hash}else{$null};output_sha256=if(Test-Path $output){(Get-FileHash $output -Algorithm SHA256).Hash}else{$null}}|ConvertTo-Json -Depth 8|Set-Content -LiteralPath (Join-Path $result 'manifest.json') -Encoding utf8
$zip="$result.zip";Compress-Archive -LiteralPath $result -DestinationPath $zip -CompressionLevel Optimal;Get-Content -Raw (Join-Path $result 'manifest.json');Write-Host "Result: $zip";exit $(if($pass){0}else{1})

